import type { DeviceInput } from "@/types/backchannel";

export const sampleParticipant: DeviceInput[] = [
  {
    deviceType: "phone",
    likeScore: 5,
    frequency: "constantly",
    lovePercent: 94,
    hateRank: 3,
    dependenceScore: 5,
  },
  {
    deviceType: "laptop",
    likeScore: 4,
    frequency: "everyday",
    lovePercent: 78,
    hateRank: 4,
    dependenceScore: 5,
  },
  {
    deviceType: "microwave",
    likeScore: 2,
    frequency: "everyday",
    lovePercent: 21,
    hateRank: 1,
    dependenceScore: 4,
  },
  {
    deviceType: "kettle",
    likeScore: 4,
    frequency: "everyday",
    lovePercent: 72,
    hateRank: 6,
    dependenceScore: 3,
  },
  {
    deviceType: "vacuum",
    likeScore: 2,
    frequency: "sometimes",
    lovePercent: 18,
    hateRank: 2,
    dependenceScore: 2,
  },
  {
    deviceType: "oven",
    likeScore: 5,
    frequency: "rarely",
    lovePercent: 84,
    hateRank: 5,
    dependenceScore: 1,
  },
];

export const defaultManualRatings: Partial<Record<DeviceInput["deviceType"], DeviceInput>> =
  {
    phone: {
      deviceType: "phone",
      likeScore: 3,
      frequency: "everyday",
      lovePercent: 60,
      hateRank: 1,
      dependenceScore: 3,
    },
    laptop: {
      deviceType: "laptop",
      likeScore: 3,
      frequency: "everyday",
      lovePercent: 60,
      hateRank: 1,
      dependenceScore: 3,
    },
    microwave: {
      deviceType: "microwave",
      likeScore: 3,
      frequency: "sometimes",
      lovePercent: 50,
      hateRank: 1,
      dependenceScore: 3,
    },
    vacuum: {
      deviceType: "vacuum",
      likeScore: 3,
      frequency: "sometimes",
      lovePercent: 50,
      hateRank: 1,
      dependenceScore: 3,
    },
    rice_cooker: {
      deviceType: "rice_cooker",
      likeScore: 3,
      frequency: "sometimes",
      lovePercent: 50,
      hateRank: 1,
      dependenceScore: 3,
    },
    kettle: {
      deviceType: "kettle",
      likeScore: 3,
      frequency: "sometimes",
      lovePercent: 50,
      hateRank: 1,
      dependenceScore: 3,
    },
    oven: {
      deviceType: "oven",
      likeScore: 3,
      frequency: "sometimes",
      lovePercent: 50,
      hateRank: 1,
      dependenceScore: 3,
    },
    dishwasher: {
      deviceType: "dishwasher",
      likeScore: 3,
      frequency: "sometimes",
      lovePercent: 50,
      hateRank: 1,
      dependenceScore: 3,
    },
    washing_machine: {
      deviceType: "washing_machine",
      likeScore: 3,
      frequency: "sometimes",
      lovePercent: 50,
      hateRank: 1,
      dependenceScore: 3,
    },
  };
