import type { DeviceArchetype, DeviceType } from "@/types/backchannel";

export const archetypesByDevice: Record<DeviceType, DeviceArchetype> = {
  phone: {
    deviceType: "phone",
    label: "Phone",
    emoji: "📱",
    baseTemperament: "main character, knows everything, possessive",
    baseRole: "keeper of attention",
    styleTags: ["nosy", "chronically online", "possessive"],
  },
  laptop: {
    deviceType: "laptop",
    label: "Laptop",
    emoji: "💻",
    baseTemperament: "workhorse, analytical, deadline trauma",
    baseRole: "keeper of output",
    styleTags: ["dry", "competent", "overworked"],
  },
  microwave: {
    deviceType: "microwave",
    label: "Microwave",
    emoji: "📡",
    baseTemperament: "speed, convenience, cynical",
    baseRole: "keeper of shortcuts",
    styleTags: ["blunt", "impatient", "snarky"],
  },
  vacuum: {
    deviceType: "vacuum",
    label: "Vacuum",
    emoji: "🌀",
    baseTemperament: "floor-level observer, notices mess",
    baseRole: "witness to collapse",
    styleTags: ["observant", "judgy", "matter-of-fact"],
  },
  rice_cooker: {
    deviceType: "rice_cooker",
    label: "Rice Cooker",
    emoji: "🍚",
    baseTemperament: "caregiver, stable, quietly judging",
    baseRole: "keeper of nourishment",
    styleTags: ["steady", "maternal", "quietly superior"],
  },
  kettle: {
    deviceType: "kettle",
    label: "Kettle",
    emoji: "🫖",
    baseTemperament: "sharp, quick, short-tempered",
    baseRole: "alarm bell of need",
    styleTags: ["fast", "sharp", "cutting"],
  },
  oven: {
    deviceType: "oven",
    label: "Oven",
    emoji: "🔥",
    baseTemperament: "aspirational, romanticized, underused",
    baseRole: "keeper of better intentions",
    styleTags: ["dramatic", "poetic", "underbooked"],
  },
  dishwasher: {
    deviceType: "dishwasher",
    label: "Dishwasher",
    emoji: "🫧",
    baseTemperament: "cleanup crew, bitter about other people’s mess",
    baseRole: "keeper of aftermath",
    styleTags: ["bitter", "service-minded", "bone-tired"],
  },
  washing_machine: {
    deviceType: "washing_machine",
    label: "Washing Machine",
    emoji: "🧺",
    baseTemperament: "handles hidden dirt, intimate labor",
    baseRole: "keeper of private residue",
    styleTags: ["intimate", "tolerant", "deeply aware"],
  },
};
